auto: true
server: false
destination: public
markdown: rdiscount
permalink: /:year/:month/:day/:title/
exclude:
  Gemfile
  Gemfile.lock
  vendor
  config.rb
  Rakefile
include:
  .htaccess
rdiscount
  extensions: [smart]
  