auto: false
server: false
destination: _site
markdown: rdiscount
permalink: /:year/:month/:day/:title/
exclude:
  Gemfile
  Gemfile.lock
  vendor
  config.rb
  Rakefile
  public
include:
  .htaccess
rdiscount
  extensions: [smart]
  