auto: false
server: false
destination: _site
plugins: _plugins
markdown: rdiscount
permalink: /:title/
exclude:
  Gemfile
  Gemfile.lock
  vendor
  config.rb
  Rakefile
  public
  tmp
include:
  .htaccess
rdiscount
  extensions: [smart]
  